AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/bundle/**/*'
    - 'spec/rails_root/**/*'
    - 'lib/generators/templates/initializer.rb'
Metrics/BlockLength:
  Exclude:
    - 'rails_spec/**/*.rb'
    - 'spec/**/*.rb'
